# Variables:
# 1. prefix - the list of prefix of the branches.
# 2. suffix - the list of suffix of the branches.

# File Structure:
# 1. all
# 2. all_branch-[].txt - all branch names with the designated prefix.
# 2. new_branch-[].txt - the "branching" code in beginJob()
# 3. push-[].txt       - the "push_back" framework for branches.
# 4. push_fail-[].txt  - the "push_back" code for failed fitting.

# Base files:
# 1. quantities.txt - the list of quantities.

.PHONY : all clean

all:

new_branch-%.txt: 

push-%.txt:

push_fail-%.txt:



clean:
